







var test = {}; (function() {


function s0() {}


function s1(a, b, f, A) {
	this.a=a; this.b=b;
	this.f=f;

	this.A={p:A}

}


function s2(microsec, serverIP6, process) {
	this.microsec=microsec;
	this.serverIP6=serverIP6;
	this.process=process
}




function Point(x, y) { this.x=x; this.y=y }



function main() {
	function Fa(a) {
		this.a=a
	}
} main();

g.Export(test, [Point]);
})();
/* Generated by Go2js (github.com/tredoe/go2js) */
