





var new_ = {}; (function() {

const static_ = 0;

const 
public_ = 0,
foo = 1,
private_ = 2;


var class_ = false;


var enum_ = g.Int(0);
var bar = g.Int(0);
var let_ = g.Int(0);


function function_(t) { this.t=t; }

function try_(private_, public_) {
	this.private_=private_;
	this.public_=public_
}

try_.prototype.with_ = function(in_) { var void_ = "", super_ = "";
	var new_ = function(this_) { var typeof_ = "";
		var v = this_;
		return v;
	};
}

function do_(in_, void_) { var super_ = "";
	return "";
}

})();
/* Generated by Go2js (github.com/tredoe/go2js) */
