





var test = {}; (function() {

const Pi = 3.14159265358979323846;
const pi2 = Pi;
const zero = 0.0;
const 
size = 1024,
eof = -1;

const a = 3, b = 4, c = "foo";
const u = 0, v = 3;



const 
Sunday = 0,
Monday = 1,
Tuesday = 2,
Wednesday = 3,
Thursday = 4,
Friday = 5,
Partyday = 6,
numberOfDays = 7;

const 
a0 = 0,
a1 = 1,
a2 = 2;

const 
b0 = 1<<0,
b1 = 1<<1,
b2 = 1<<2;

const 
c0 = 0 * 42,
c1 = 1 * 42,
c2 = 2 * 42;


const x = 0;
const y = 0;

const 
bit0 = 1<<0, mask0 = 1<<0 - 1,
bit1 = 1<<1, mask1 = 1<<1 - 1,

bit3 = 1<<3, mask3 = 1<<3 - 1;


function main() {
	const F = 1;

	const 
	Fa = 2,
	fb = 3;

} main();

g.Export(test, [Pi, Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Partyday]);
})();
/* Generated by Go2js (github.com/tredoe/go2js) */
