









var PASS = true;


var u = g.Uint(1);
var u_ = g.Uint(1);
var u8 = g.Uint8(8);
var u16 = g.Uint16(16);
var u32 = g.Uint32(32);

var i = g.Int(-1);
var i_ = g.Int(-1);
var i8 = g.Int8(-8);
var i16 = g.Int16(-16);
var i32 = g.Int32(-32);

var f32 = g.Float32(3.2);
var f32_ = g.Float32(3.2);
var f64 = g.Float64(6.4);
var f64_ = g.Float64(6.4);

var b = g.Byte(8);
var b_ = g.Byte(8);

var r = g.Rune(32);
var r_ = g.Rune(32);







function value() {
	var pass = true;

	if (u != 1 || u_ != 1 || u8 != 8 || u16 != 16 || u32 != 32) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: uint<br>");
		pass = false, PASS = false;
	}
	if (i != -1 || i_ != -1 || i8 != -8 || i16 != -16 || i32 != -32) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: int<br>");
		pass = false, PASS = false;
	}
	if (f32 != 3.2 || f32_ != 3.2 || f64 != 6.4 || f64_ != 6.4) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: float<br>");
		pass = false, PASS = false;
	}
	if (b != 8 || b_ != 8) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: byte<br>");
		pass = false, PASS = false;
	}
	if (r != 32 || r_ != 32) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: rune<br>");
		pass = false, PASS = false;
	}

	if (pass) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;pass<br>");
	}
}

function calculation() {
	var pass = true;

	if (u + 1 != 2 || u_ + 1 != 2 || u8 + 1 != 9 || u16 + 1 != 17 || u32 + 1 != 33) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: add uint<br>");
		pass = false, PASS = false;
	}
	if (i + 1 != 0 || i_ + 1 != 0 || i8 + 1 != -7 || i16 + 1 != -15 || i32 + 1 != -31) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: add int<br>");
		pass = false, PASS = false;
	}
	if (f32 + 1 != 4.2 || f32_ + 1 != 4.2 || f64 + 1 != 7.4 || f64_ + 1 != 7.4) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: add float<br>");
		pass = false, PASS = false;
	}
	if (b + 1 != 9 || b_ + 1 != 9) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: add byte<br>");
		pass = false, PASS = false;
	}
	if (r + 1 != 33 || r_ + 1 != 33) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: add rune<br>");
		pass = false, PASS = false;
	}

	if (u8 - 1 != 7 || i8 - 1 != -9 || f32 - 1 != 2.2 || b - 1 != 7 || r - 1 != 31) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: subtract<br>");
		pass = false, PASS = false;
	}

	if (u16 * 2 != 32 || i16 * 2 != -32 || f64 * 2 != 12.8 || b * 2 != 16 || r * 2 != 64) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: multiplication<br>");
		pass = false, PASS = false;
	}

	if (u / 1 != 1 || i / 1 != -1 || f32 / 2 != 1.6 || b / 2 != 4 || r / 2 != 16) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: division (quotient)<br>");
		pass = false, PASS = false;
	}
	if (u8 % 3 != 2 || u16 % 3 != 1 || i8 % 3 != -2 || i16 % 3 != -1) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: division (remainder)<br>");
		pass = false, PASS = false;
	}

	if (pass) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;pass<br>");
	}
}

function bitwise() {
	var pass = true;

	if (u16>>1 != 8 || u16<<1 != 32 || i16>>1 != -8 || i16<<1 != -32) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: Shift<br>");
		pass = false, PASS = false;
	}

	if ((7&9) != 1 || (-7&9) != 9) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: AND<br>");
		pass = false, PASS = false;
	}

	if ((7|9) != 15 || (-7|9) != -7) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: OR<br>");
		pass = false, PASS = false;
	}

	if ((7^9) != 14 || (-7^9) != -16) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: XOR<br>");
		pass = false, PASS = false;
	}

	if ((7&~9) != 6 || (-7&~9) != -16) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: AND NOT<br>");
		pass = false, PASS = false;
	}

	var n = 7;
	n &= ~(9);
	if (n != 6) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: AND NOT (assignment)<br>");
		pass = false, PASS = false;
	}

	if (~-7 != 6 || ~7 != -8) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;FAIL: NOT<br>");
		pass = false, PASS = false;
	}

	if (pass) {
		document.write("&nbsp;&nbsp;&nbsp;&nbsp;pass<br>");
	}
}

function main() {
	document.write("<br><br>== Numeric<br><br>");

	document.write("=== RUN value<br>");
	value();
	document.write("=== RUN calculation<br>");
	calculation();
	document.write("=== RUN bitwise<br>");
	bitwise();

	if (PASS) {
		document.write("PASS<br>");
	} else {
		document.write("FAIL<br>");
		alert("Fail: Numeric");
	}
} main();
/* Generated by Go2js (github.com/tredoe/go2js) */
